
"COMMAND 1 = SHORT RANGE SENSOR SCAN"
"  PRINTS THE QUADRANT YOU ARE CURRENTLY IN, INCLUDING"
"  STARS, KLINGONS, STARBASES, AND THE ENTERPRISE; ALONG"
"  WITH OTHER PERTINATE INFORMATION."

"COMMAND 2 = LONG RANGE SENSOR SCAN"
"  SHOWS CONDITIONS IN SPACE FOR ONE QUADRANT ON EACH SIDE"
"  OF THE ENTERPRISE IN THE MIDDLE OF THE SCAN.  THE SCAN"
"  IS CODED IN THE FORM XXX, WHERE THE UNITS DIGIT IS THE"
"  NUMBER OF STARS, THE TENS DIGIT IS THE NUMBER OF STAR-"
"  BASES, THE HUNDREDS DIGIT IS THE NUMBER OF KLINGONS."

"COMMAND 3 = PHASER CONTROL"
"  ALLOWS YOU TO DESTROY THE KLINGONS BY HITTING HIM WITH"
"  SUITABLY LARGE NUMBERS OF ENERGY UNITS TO DEPLETE HIS "
"  SHIELD POWER.  KEEP IN MIND THAT WHEN YOU SHOOT AT"
"  HIM, HE GONNA DO IT TO YOU TOO."
A != 2) goto _615
I = 1; I <= 5; I += 1)

      _6154: ;}
 "ENTER A NUMBER TO CONTINUE...  "
out I


"COMMAND 4 = PHOTON TORPEDO CONTROL"
"  COURSE IS THE SAME AS USED IN WARP ENGINE CONTROL"
"  IF YOU HIT THE KLINGON, HE IS DESTROYED AND CANNOT FIRE"
"  BACK AT YOU.  IF YOU MISS, HE WILL SHOOT HIS PHASERS AT"
"  YOU."
"   NOTE: THE LIBRARY COMPUTER (COMMAND 7) HAS AN OPTION"
"   TO COMPUTE TORPEDO TRAJECTORY FOR YOU (OPTION 2)."

"COMMAND 5 = SHIELD CONTROL"
"  DEFINES NUMBER OF ENERGY UNITS TO ASSIGN TO SHIELDS"
"  ENERGY IS TAKEN FROM TOTAL SHIP'S ENERGY."

"COMMAND 6 = DAMAGE CONTROL REPORT"
"  GIVES STATE OF REPAIRS OF ALL DEVICES."
"  A STATE OF REPAIR"
"  LESS THAN ZERO SHOWS THAT THAT DEVICE IS TEMPORARALY"
"  DAMAGED."
A != 2) goto _629
I = 1; I <= 6; I += 1)

      _6294: ;}
 "ENTER A NUMBER TO CONTINUE...  "
out I


 "COMMAND 7 = LIBRARY COMPUTER"
 "  THE LIBRARY COMPUTER CONTAINS THREE OPTIONS:"
 "    OPTION 0 = CUMULATIVE GALACTIC RECORD"
 "     SHOWS COMPUTER MEMORY OF THE RESULTS OF ALL PREVIOUS"
 "     LONG RANGE SENSOR SCANS"
 "    OPTION 1 = STATUS REPORT"
 "     SHOWS NUMBER OF KLINGONS, STARDATES AND STARBASES"
 "     LEFT."
 "    OPTION 2 = PHOTON TORPEDO DATA"
 "     GIVES TRAJECTORY AND DISTANCE BETWEEN THE ENTERPRISE"
 "     AND ALL KLINGONS IN YOUR QUADRANT"

